substitutions:
  temperature_id: temperature
  temperature_name: ${name_prefix} temperature
  humidity_id: humidity
  humidity_name: ${name_prefix} humidity
  update_interval: 10s

sensor: 
  - platform: sht3xd
    temperature:
      id: ${temperature_id}
      name: ${temperature_name}
      accuracy_decimals: 2
      unit_of_measurement: Â°C
    humidity:
      id: ${humidity_id}
      name: ${humidity_name}
      accuracy_decimals: 1
      unit_of_measurement: "%"
    update_interval: ${update_interval}