api_key: EhejqKo8hVTV/GhGUBgNYmWgMIPrnFRClpeLW5bn2ew=

network_gateway: "10.0.0.1"
network_subnet: "255.255.255.0"
ota_password: ota_password
web_password: web_password
wifi_essid: wifi_essid
wifi_password: wifi_password
device_area: "Test Area"
device_name: test-device

network_address: 10.0.0.100
