network_gateway: "10.0.0.1"
network_subnet: "255.255.255.0"
ota_password: !secret ota_password
web_password: !secret web_password
wifi_essid: !secret wifi_essid
wifi_password: !secret wifi_password
device_area: "Test Area"
