substitutions:
  button_name: button
  switch_name: relay
  blue_led_name: blue LED

esphome:
  platform: ESP8266
  board: esp8285

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle:
          id: relay

  - platform: gpio
    name: ${button_name}
    pin: GPIO04
    id: button
    on_press:
      then:
        - switch.toggle:
            id: relay
    on_release:
      then:
        - switch.toggle:
            id: relay

switch:
  - platform: gpio
    name: switch
    pin: GPIO12
    id: relay
    restore_mode: restore_default_off

status_led:
  pin:
    number: GPIO13
    allow_other_uses: true
    inverted: true

output:
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO13
      allow_other_uses: true
    inverted: True

light:
  - platform: monochromatic
    name: ${blue_led_name}
    output: blue_led
    # internal: true
