# https://esphome.io/components/spi.html

substitutions:
  id: spi_1
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  interface: hardware

spi:
  - id: ${id}
    clk_pin: ${clk_pin}
    mosi_pin: ${mosi_pin}
    miso_pin: ${miso_pin}
    interface: ${interface}
