substitutions:
  network_primary_name_server: 1.1.1.1
  network_secondary_name_server: 8.8.8.8

wifi:
  min_auth_mode: WPA2
  manual_ip:
    dns1: ${network_primary_name_server}
    dns2: ${network_secondary_name_server}
  domain: ${network_domain}
