substitutions:
  device_name: device
  device_area: ""
  friendly_name: ${device_name}
  name_prefix: ""
  mqtt_port: "1883"
  mqtt_prefix: ${device_name}

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${device_area}

mqtt:
  broker: ${mqtt_host}
  port: ${mqtt_port}
  username: ${mqtt_user}
  password: ${mqtt_password}
  topic_prefix: ${mqtt_prefix}

ota:
  - platform: esphome
    password: ${ota_password}

packages:
  status: !include ../../packages/component/binary-sensor/status.yaml
  version: !include ../../packages/component/text-sensor/version.yaml
  uptime: !include ../../packages/component/sensor/uptime.yaml
  logger: !include ../../packages/component/logger.yaml
  restart: !include ../../packages/component/button/restart.yaml
