# https://esphome.io/components/text_sensor/ethernet_info

text_sensor:
  - platform: ethernet_info
    ip_address:
      name: ${device_name} IP address
      entity_category: diagnostic
    mac_address:
      name: ${device_name} MAC address
      entity_category: diagnostic
