# https://github.com/trombik/esphome-component-ping

substitutions:
  ping_name: ping probe
  ip_address: 1.1.1.1
  num_attempts: '10'
  timeout: 1sec
  update_interval: 10s

sensor:
  - platform: ping
    ip_address: ${ip_address}
    num_attempts: ${num_attempts}
    timeout: ${timeout}
    loss:
      name: ${ping_name} packet loss
    latency:
      name: ${ping_name} latency
      accuracy_decimals: 3
    update_interval: ${update_interval}
